service: HerokuLogs
provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  stage: ${opt:stage}

functions:
  index:
    handler: handler.lambda_handler
    events:
      - http: POST hello

custom:
  pythonRequirements:
    dockerizePip: false

plugins:
  - serverless-python-requirements
